name: HelloWorkflow

on: [push]

jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: ShowMessage
        run: echo "HelloWorkflow"
       
      - name: Checkout
        uses: actions/checkout@v4
       
      - name: ListDir
        run: ls -alh
        
      - name: SetupPython
        uses: actions/setup-python@v5
        with:
            python-version: "3.10"

      - name: CheckPythonVersion
        run: python --version

      - name: RunPython
        run: python app.py
      