name: HelloWorkflow

on: [push]

jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: ShowMessage
        run: echo "HelloWorkflow"
       
      - name: Checkout
        uses: actions/checkout@v4
       
      - name: ListDir
        run: ls -alh
      
      